=== janesp/VoyagerBase/composeApp/src/commonMain/composeResources/files/prescription-item-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "PrescriptionItem",
  "type": "object",
  "properties": {
    "medicationId": {
      "type": "string",
      "description": "Unique identifier for the medication"
    },
    "name": {
      "type": "string",
      "description": "Name of the medication"
    },
    "dose": {
      "type": "string",
      "description": "Dosage information"
    },
    "frequency": {
      "type": "string",
      "description": "Frequency of medication intake"
    },
    "duration": {
      "type": "string",
      "description": "Duration for which the medication is to be taken"
    }
  },
  "required": ["medicationId", "name", "dose", "frequency", "duration"]
}

=== janesp/VoyagerBase/composeApp/src/commonMain/composeResources/files/prescription_items.json
[
  {
    "medicationId": "med001",
    "name": "Amoxicillin",
    "dose": "500mg",
    "frequency": "3 times a day",
    "duration": "7 days"
  },
  {
    "medicationId": "med002",
    "name": "Ibuprofen",
    "dose": "200mg",
    "frequency": "every 4-6 hours as needed",
    "duration": "5 days"
  },
  {
    "medicationId": "med003",
    "name": "Lisinopril",
    "dose": "10mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med004",
    "name": "Metformin",
    "dose": "500mg",
    "frequency": "twice a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med005",
    "name": "Amlodipine",
    "dose": "5mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med006",
    "name": "Omeprazole",
    "dose": "20mg",
    "frequency": "once a day",
    "duration": "14 days"
  },
  {
    "medicationId": "med007",
    "name": "Atorvastatin",
    "dose": "10mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med008",
    "name": "Simvastatin",
    "dose": "20mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med009",
    "name": "Azithromycin",
    "dose": "250mg",
    "frequency": "once a day",
    "duration": "5 days"
  },
  {
    "medicationId": "med010",
    "name": "Albuterol",
    "dose": "2 puffs",
    "frequency": "every 4-6 hours as needed",
    "duration": "as needed"
  },
  {
    "medicationId": "med011",
    "name": "Levothyroxine",
    "dose": "75mcg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med012",
    "name": "Prednisone",
    "dose": "20mg",
    "frequency": "once a day",
    "duration": "10 days"
  },
  {
    "medicationId": "med013",
    "name": "Hydrochlorothiazide",
    "dose": "25mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med014",
    "name": "Gabapentin",
    "dose": "300mg",
    "frequency": "3 times a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med015",
    "name": "Clindamycin",
    "dose": "300mg",
    "frequency": "4 times a day",
    "duration": "7 days"
  },
  {
    "medicationId": "med016",
    "name": "Zolpidem",
    "dose": "10mg",
    "frequency": "once a day at bedtime",
    "duration": "14 days"
  },
  {
    "medicationId": "med017",
    "name": "Ciprofloxacin",
    "dose": "500mg",
    "frequency": "twice a day",
    "duration": "10 days"
  },
  {
    "medicationId": "med018",
    "name": "Citalopram",
    "dose": "20mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med019",
    "name": "Doxycycline",
    "dose": "100mg",
    "frequency": "twice a day",
    "duration": "10 days"
  },
  {
    "medicationId": "med020",
    "name": "Sertraline",
    "dose": "50mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med021",
    "name": "Fluticasone",
    "dose": "1 spray each nostril",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med022",
    "name": "Montelukast",
    "dose": "10mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med023",
    "name": "Amoxicillin/Clavulanate",
    "dose": "875mg/125mg",
    "frequency": "twice a day",
    "duration": "10 days"
  },
  {
    "medicationId": "med024",
    "name": "Tramadol",
    "dose": "50mg",
    "frequency": "every 4-6 hours as needed",
    "duration": "7 days"
  },
  {
    "medicationId": "med025",
    "name": "Metoprolol",
    "dose": "50mg",
    "frequency": "twice a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med026",
    "name": "Tamsulosin",
    "dose": "0.4mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med027",
    "name": "Losartan",
    "dose": "50mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med028",
    "name": "Furosemide",
    "dose": "40mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med029",
    "name": "Bupropion",
    "dose": "150mg",
    "frequency": "once a day",
    "duration": "30 days"
  },
  {
    "medicationId": "med030",
    "name": "Escitalopram",
    "dose": "10mg",
    "frequency": "once a day",
    "duration": "30 days"
  }
]
